### ISSUE TITLE
Wrong Shipping Calculations When Using Discounts

### ISSUE THREAD

**Issue by patrickheeney** [damanic/ls1-module-shop#12] opened 2021-02-09 01:48 UTC
Hello, I finally got an old Lemonstand install brought up to date with all the latest modules, such a big changeset! However we noticed our shipping calculation discounts stopped working.

We have a discount set to apply free shipping to a specific product in cart (gift certificate). With only the one item in cart you would expect free shipping. With more than one item in cart, the item gets essentially removed from the calculations so only the remaining items are totalled. This happens to be how it used to work prior to the updating within LS. 

I am not familiar with all the changes yet, but here is what I can tell so far, but this entire section: https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1184-L1287 in the old LS methods seems dedicated to calculating the free shipping items.

I don't see that same functionality implemented in the new method ```Shop_ShippingOption::fetch_quote()``` that replaced this one. 

Secondly, is there a way to opt out of the new methods in the time being. I can't easily revert due to the amount of other impacted changes. It looks like I can disable the caching as it doesn't look to apply any discounts related to items in the cart.

**Comment by patrickheeney** [comment] 2021-02-09 15:47
I am going to start logging the issues I found while trying to debug this here and break them out into PRs later. 

This change and line introduced a bug: https://github.com/damanic/ls1-module-shop/commit/981bf5236a3d2a844f183824b2e2fb3e3aefe2ff#diff-11fc4ca556a4b5fed84fa5ec99e2f79db12b72de3e56cf0f334bb9f4c02ca56fR65

The old logic here: https://github.com/damanic/ls1-module-shop/commit/981bf5236a3d2a844f183824b2e2fb3e3aefe2ff#diff-11fc4ca556a4b5fed84fa5ec99e2f79db12b72de3e56cf0f334bb9f4c02ca56fL72 checked for ```$attribute = product``` and now it is checking if ```$attribute = price``` which is incorrect.

**Comment by patrickheeney** [comment] 2021-02-09 16:13
This line introduced a bug: https://github.com/damanic/ls1-module-shop/commit/8d36d2f94b40bc4aa303332ba17b5d615dd5beb8#diff-39b54fc33738d6f40f946f61f55abe1a532648b72e62a3d1b4ae35fcef3f9f89R1342 and this line: https://github.com/damanic/ls1-module-shop/commit/8d36d2f94b40bc4aa303332ba17b5d615dd5beb8#diff-39b54fc33738d6f40f946f61f55abe1a532648b72e62a3d1b4ae35fcef3f9f89R879

It used to be ```$include_tax !== 1``` which got changed to ```$include_tax``` and since ```include_tax = 1``` by default, the logic got changed to always include the tax by default.

**Comment by patrickheeney** [comment] 2021-02-09 16:19
Total Weight was passed an option to this method https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1343 but is not included in the parameters passed to the new method: https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1351

There is also no default https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L916 for the new method when the parameter is used https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L947

**Comment by patrickheeney** [comment] 2021-02-09 16:30
```is_business``` in this method https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1343 is not passed to https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1345 which later gets pulled back out https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L983 which means the value ends up always ```null``` instead of the real value.

**Comment by patrickheeney** [comment] 2021-02-09 16:36
The default values never get set https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L544 like they do in other methods https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L611 for depreciated values.

**Comment by patrickheeney** [comment] 2021-02-09 17:47
I was able to resolve it. The issue is that the new methods do not apply the discounts prior to retrieving the quote, but rather after. Since the discounts can apply free shipping or modify the cart contents, it needs to be applied prior to retrieving the quote. It also means any events fired before or after the quote is generated also do not take into account any discounts. 

Once modified to apply discounts prior to the quote calculation, this entire section was not implemented in the new methods: https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1240-L1287 which merges the new quote into the old one. I am not sure why LS fires off the quote twice rather than once since we know the discounts before hand but I am not aware of the decisions that lead them to implementing it so I copy and pasted the logic as is.

**Comment by damanic** [comment] 2021-02-10 03:19
It might take me a while to get through these. 

Looking at this one today:

> I am going to start logging the issues I found while trying to debug this here and break them out into PRs later.
> 
> This change and line introduced a bug: [981bf52#diff-11fc4ca556a4b5fed84fa5ec99e2f79db12b72de3e56cf0f334bb9f4c02ca56fR65](https://github.com/damanic/ls1-module-shop/commit/981bf5236a3d2a844f183824b2e2fb3e3aefe2ff#diff-11fc4ca556a4b5fed84fa5ec99e2f79db12b72de3e56cf0f334bb9f4c02ca56fR65)
> 
> The old logic here: [981bf52#diff-11fc4ca556a4b5fed84fa5ec99e2f79db12b72de3e56cf0f334bb9f4c02ca56fL72](https://github.com/damanic/ls1-module-shop/commit/981bf5236a3d2a844f183824b2e2fb3e3aefe2ff#diff-11fc4ca556a4b5fed84fa5ec99e2f79db12b72de3e56cf0f334bb9f4c02ca56fL72) checked for `$attribute = product` and now it is checking if `$attribute = price` which is incorrect.

Agree.  Correct product operators appeared to be maintained regardless but the option to compare price was being restricted to the `is` operator.  Can't think of why that restriction would have been put in other than typo or copy!  


Fixed in: https://github.com/damanic/ls1-module-shop/commit/7f1eef99236ec6d1b24ea0bdfc128e21e78e891b

**Comment by patrickheeney** [comment] 2021-02-10 15:05
I can submit a PR for all of it. I was mainly using the issue to document
my findings so I didn’t forget to submit a patch.

**Comment by damanic** [comment] 2021-02-16 03:25
The method Shop_ShippingOption::fetch_quote  accepts a basic set of parameters. This can be used directly outside of cart/order/discount/cache context to get a quote from the provider. Eg.  You could use it to service a shipping calculator where backend user enters package dimensions and weights.

It is used by an internal _quote() method that supports cache. Which in turn is made public via two context based methods

- Shop_ShippingOption::apply_order_quote()
    - This does not re-evaluate discount rules prior to fetching quotes
- Shop_ShippingOption::apply_checkout_quote()
     - This applies discount rules prior to fetching quotes
     - Any free shipping applied to cart items (zero weighting) ahead of quote is factored in by using Shop_Cart::total_items_weight()



One of the many issues with the deprecated methods was that items marked as free shipping were being ommitted from shipping quote parameters. This caused issues with shipping providers that support shipments with customs declarations and packing advice/notes.  So to correct this the weight and dimensions that impact the cost of shipping are ignored, not the items.  

If you want to exclude a gift certificate from being included in shipping quotes, you do not need to use a discount rule. You can assign the product to a product type that does not enable shipping. Eg. 'downloadable'



--------------------


> I was able to resolve it. The issue is that the new methods do not apply the discounts prior to retrieving the quote, but rather after. Since the discounts can apply free shipping or modify the cart contents, it needs to be applied prior to retrieving the quote. It also means any events fired before or after the quote is generated also do not take into account any discounts.
> 
> Once modified to apply discounts prior to the quote calculation, this entire section was not implemented in the new methods: https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1240-L1287 which merges the new quote into the old one. I am not sure why LS fires off the quote twice rather than once since we know the discounts before hand but I am not aware of the decisions that lead them to implementing it so I copy and pasted the logic as is.

**Comment by patrickheeney** [comment] 2021-02-16 06:00
The main issue with that is the change in logic. The discount engine allows
you to mark items as free shipping and previously those items were removed
prior to fetching a quote. This change in behavior is not backwards
compatible with how the discount engine works. I understand what you are
saying about the particular example of a gift card. However this one site
has many different types of products and some are conditionally shipped
based on the rules of the discount engine and some of them are not shipped.
It is not as easy as marking them as a specific product type as it is
conditional. As it stands now the discount engine logic of applying free
shipping to items is not compatible at all with the latest updates. I could
submit a PR but as you pointed out that would not be compatible with the
updates that rely on the items existing for the third parties.

I did find that the discounts were not applied when LS internally call it,
not the new apply methods prior to fetching the quote. It applied it after.
This means any discounts rules that modify what gets sent to the quote were
not factored in. The original LS did run these rules prior.

**Comment by damanic** [comment] 2021-02-16 07:49
> As it stands now the discount engine logic of applying free
shipping to items is not compatible at all with the latest updates. 

I am not seeing this.   Perhaps you are using a custom discount rule?   If not, can you post steps to reproduce.

If you set your shipping methods to only quote at a weight of 0.001 upwards, and your free shipping method to apply at 0  , you will see free shipping offered for orders where all items are marked as `free_shipping` by a discount rule.

**Comment by patrickheeney** [comment] 2021-02-16 15:28
I don't have the code in front of me at the moment, but I will try to use the github code as an example. 

The discount rule is a standard lemonstand one as seen here: https://github.com/damanic/ls1-module-shop/blob/master/price_rule_actions/shop_cartproductfreeshipping_action.php#L58 which marks the item as free shipping.

In original LS, the discount is evaluated before https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1175 the quote https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1235 and then the quote is also refetched https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1260

In the new version the quote is requested https://github.com/damanic/ls1-module-shop/blob/master/models/shop_shippingoption.php#L1004 first and then applied https://github.com/damanic/ls1-module-shop/blob/c2ab7181f53b0bbdfe3a0ee1e94548ca86a0528e/models/shop_shippingoption.php#L1008 which adds the discount https://github.com/damanic/ls1-module-shop/blob/c2ab7181f53b0bbdfe3a0ee1e94548ca86a0528e/models/shop_shippingoption.php#L711 after the quote was generated. In all new methods the quote is requested prior to being applied.

My fix was to add the free shipping logic back prior to requesting the quote in all 3 cases so the discount would apply prior to passing it _get_quote.

**Comment by patrickheeney** [comment] 2021-02-16 15:34
To replicate, create a discount in the discount engine (One of Product discount) that sets an item to free shipping. Maybe also set that product to have a weight and a rate table shipping that uses that weight. During checkout the discount is not applied first which means the items are passed to the shipping option. The shipping option keeps them in tact which means it adds the weight of the product that is supposed to ship for free into the rate tables.

If you use a rate based shipping, its a good indicator because you can have different types of products that impact the shipping. For example you have two $10 products and a rate table that says $10 ships for $2.99 and $20 ships for $9.99. As it currently stands it uses the $9.99 rate even though one item ships for free. LS originally removed that item thus the subtotal was back to $10 and used the correct $2.99 rate.

A real world example. Lets say you have some products that are heavy and have a per product based shipping cost. However if you order a certain volume they will ship that specific item for free. The items can't be a digital good and their real weight is needed to calculate the actual shipping, but some customers will see free shipping.

Or lets say you have a catalog that has an actual weight. However certain types of customers (commercial) can request a catalog for free while residential would pay normal shipping rates. The discount engine would determine the type and apply free shipping for that customer type. 

In all these examples they are not digitial like a gift card. They also have a real weight that factors into the shipping cost, but there are conditions the discount engine evaluates that marks them as free in specific situations. What I mean by it is no longer compatible is that original LS supported these use cases and the new code doesn't take this into account. After applying the update none of the discount engine rules continued to work and I had to create some new code to emulate what LS used to do by evaluating the discount rules first and then adding back in the handling of free shipping.

**Comment by damanic** [comment] 2021-02-18 05:39
@patrickheeney 

I have set up the following on a fresh LS install updated to latest shop module versions (shop v1.35.3).

I  added a discount rule with Action `Apply free shipping to cart products specified below` . Set product specification to `Product is one of (baseballcap)`
![image](https://user-images.githubusercontent.com/5227303/108306625-aba1b480-7200-11eb-815c-d6f9935ddbfb.png)

------------------

Added a flat rate shipping method and free shipping method as shown:
![image](https://user-images.githubusercontent.com/5227303/108306705-dc81e980-7200-11eb-8a71-73b225f62f33.png)

------------------

Set valid dimensions and weight on baseball cap.  Set valid dimension and weight on Sneakers.  

With both items in the cart, flat rate shipping is offered (because of sneaker weight)
![image](https://user-images.githubusercontent.com/5227303/108306916-4ac6ac00-7201-11eb-8854-d00565e38c48.png)

---------------

With only baseball cap in cart, free shipping is offered because the weight of the cap has been discounted by the discount rule.
![image](https://user-images.githubusercontent.com/5227303/108306951-5a45f500-7201-11eb-92d1-d2283683d7c8.png)

---------------

The same result on checkout:
![image](https://user-images.githubusercontent.com/5227303/108307305-ad1fac80-7201-11eb-9394-790ef62d32a1.png)

---------------
And here is checkout refreshed with the discount rule de-activated:
![image](https://user-images.githubusercontent.com/5227303/108307862-c2e1a180-7202-11eb-80a1-046c09a5ee16.png)

---------------

So the weight/dimension of cart items is being discounted  by the discount rule prior to shipping rates being evaluated.  You should get the same result

------------------------

**I suspect the issue we have here is at the shipping provider/type end. They should be using  :**

Shop_CartItem::weight();
Shop_CartItem::depth();
Shop_CartItem::width();
Shop_CartItem::height();
_Shop_CartItem::total_*()_

And they should make use of the $include_free_shipping parameter for those methods.   Looking at it now I can see the following shipping methods are likely affected:

- USPS is not setting $include_free_shipping = false 
- FEDEX  + CANADAPOST  are not using cart item methods at all, and getting weight/volume from the product record - so not even compatible with option matrix!

All the installs I manage are plugged into EasyPost, so this is the first time I have been called to look at the old shipping drivers in quite some time!

-----------

__EDIT/UPDATE__

USPS use of  $include_free_shipping = true is only on label generation which is correct.
On frontend quote it uses the passed parameter `total_weight` , which does discount free shipping weight  
BUT
It is failing at volume (not option matrix compatible or excluding free ship items) : `$total_volume += ($cart_item->product->depth * $cart_item->product->width * $cart_item->product->height) * $cart_item->quantity;`

**Comment by patrickheeney** [comment] 2021-02-18 06:15
Definitely not using easy post here but I don’t recall which driver so I
will double check on my end as well.

Another thing is I don’t recall them having a free shipping method. Only
the items get marked as free shipping for a $0 quote but it never changes
the shipping method just reduces the cost. I am not sure if that plays a
factor. I’ll have to confirm this on my end again as well.

What does the conditions and free shipping tab look like on your discount
engine. Conditions should be similar to be one of the item. And free
shipping should have no selected. At least for this particular use case.

**Comment by damanic** [comment] 2021-02-18 06:38
> What does the conditions and free shipping tab look like on your discount
engine. Conditions should be similar to be one of the item. And free
shipping should have no selected. At least for this particular use case.


It was a new rule with everything left blank/default apart from :

- Name
- Description
- The settings shown on the action tab. 
    - https://user-images.githubusercontent.com/5227303/108306625-aba1b480-7200-11eb-815c-d6f9935ddbfb.png

No ticks on the free shipping tab. Nothing on the Conditions tab.

**Comment by patrickheeney** [comment] 2021-02-18 16:20
Not sure any of this is related, but still trying to track down where this install is different. 

Discount Rule Conditions
- All subconditions must be TRUE
-  -  Shopping cart item presence condition (Item is FOUND in the shopping cart) (All subconditions should be TRUE)
-  -  - Product is ONE OF (Baseball cap)

Shipping Methods
- Only one Table Rate method, no free shipping. No min or max weight.
- Rates are based on subtotal
![Screen Shot 2021-02-18 at 8 37 51 AM](https://user-images.githubusercontent.com/1407228/108381089-b5a5c200-71c4-11eb-871f-4543e5f83663.png)

Tracing through the deprecated code:
- This section https://github.com/damanic/ls1-module-shop/blob/0df1448b4a8a29f4f392af6d02420150a33dcd98/models/shop_shippingoption.php#L1184-L1201 creates a new array of non-free shipping items. Then it loops through those and re-tallys up the item stats and uses that to fire off an event new quote. 
- Where has this behavior moved to? If it was removed because you need those items to be passed to the shipping method quote, then isn't that a change in behavior?

**Comment by patrickheeney** [comment] 2021-02-18 16:24
It also appears you might be checking for shipping methods on the cart page. This shop does not have that and is getting the shipping methods from ```shop:checkout``` actions during the ```shipping_info``` step. Might be something different happening during checkout.

**Comment by damanic** [comment] 2023-03-08 04:25
Fixed in 
https://github.com/damanic/ls1-module-shop/releases/tag/1.39.1

**Closed as completed by damanic** 2023-03-08 04:25 UTC
