### ISSUE TITLE
Undefined property: Shop_Product::$id

### ISSUE THREAD

**Issue by jimbolinos** [damanic/ls1-module-shop#13] opened 2022-02-08 09:49 UTC
Hi there,

Just came to add products and came up with the following error:

`Undefined property: Shop_Product::$id`

The same also happens when duplicating and trying to import via csv. Everything is up to date, but I haven't added anything new for 12 months or so, so I'm not entirely sure what update may have caused this.

Error seems to be in
`/phproad/modules/db/classes/db_activerecord.php, line 1514`

Thanks,

James

**Comment by damanic** [comment] 2022-02-09 00:28
I am not convinced that this has been caused by an update in this repo. 

The line pointed to has not been changed, and the ID property is loaded in dynamically for Shop_Product so I suspect it has always been undefined when creating a new record.

There is certainly an issue here, but I think it is a long standing one.

LS will run just fine on PHP7 so long as strict/notice/warning errors are turned off in your environment.

**Comment by damanic** [comment] 2022-02-09 00:32
> Error seems to be in
> /phproad/modules/db/classes/db_activerecord.php, line 1514

Addressed in 
https://github.com/damanic/ls1-phproad/commit/40fbcc7869b38ca9ab8a8baa6be48f208fc3a27f

**Closed as completed** 2022-02-09 00:32 UTC
